/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ristekCalculator;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public int addition(int num1, int num2) {
        return num1 + num2;
    }

    public int subtraction(int num1, int num2) {
        return num1 - num2;
    }

    public int multiplication(int num1, int num2) {
        return num1 * num2;
    }

    public int multiplication(int num1, int num2) {
        return num1 / num2;
    }


    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
