/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ristekCalculator;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test public void testAppAdditionPosPos() {
        App classUnderTest = new App();
        assertEquals(15, classUnderTest.addition(8,7));
    }

    @Test public void testAppAdditionPosNeg() {
        App classUnderTest = new App();
        assertEquals(-3, classUnderTest.addition(7,-10));
    }

    @Test public void testAppAdditionNegNeg() {
        App classUnderTest = new App();
        assertEquals(-12, classUnderTest.addition(-9,-3));
    }

    @Test public void testAppSubtractionPosPos() {
        App classUnderTest = new App();
        assertEquals(1, classUnderTest.subtraction(8, 7));
    }

    @Test public void testAppSubtractionPosNeg() {
        App classUnderTest = new App();
        assertEquals(17, classUnderTest.subtraction(7, -10));
    }

    @Test public void testAppSubtractionNegPos() {
        App classUnderTest = new App();
        assertEquals(-17, classUnderTest.subtraction(-10, 7));
    }

    @Test public void testAppSubtractionNegNeg() {
        App classUnderTest = new App();
        assertEquals(-6, classUnderTest.subtraction(-9, -3));
    }
}
