/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ristekCalculator;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.jupiter.api.Assertions;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test public void testAppAdditionPosPos() {
        App classUnderTest = new App();
        assertEquals(15, classUnderTest.addition(8,7));
    }

    @Test public void testAppAdditionPosNeg() {
        App classUnderTest = new App();
        assertEquals(-3, classUnderTest.addition(7,-10));
    }

    @Test public void testAppAdditionNegNeg() {
        App classUnderTest = new App();
        assertEquals(-12, classUnderTest.addition(-9,-3));
    }

    @Test public void testAppSubtractionPosPos() {
        App classUnderTest = new App();
        assertEquals(1, classUnderTest.subtraction(8, 7));
    }

    @Test public void testAppSubtractionPosNeg() {
        App classUnderTest = new App();
        assertEquals(17, classUnderTest.subtraction(7, -10));
    }

    @Test public void testAppSubtractionNegPos() {
        App classUnderTest = new App();
        assertEquals(-17, classUnderTest.subtraction(-10, 7));
    }

    @Test public void testAppSubtractionNegNeg() {
        App classUnderTest = new App();
        assertEquals(-6, classUnderTest.subtraction(-9, -3));
    }

    @Test public void testAppMultiplicationPosPos() {
        App classUnderTest = new App();
        assertEquals(27, classUnderTest.multiplication(9, 3));
    }

    @Test public void testAppMultiplicationNegNeg() {
        App classUnderTest = new App();
        assertEquals(27, classUnderTest.multiplication(-9, -3));
    }

    @Test public void testAppMultiplicationPosNeg() {
        App classUnderTest = new App();
        assertEquals(-27, classUnderTest.multiplication(9, -3));
    }

    @Test public void testAppMultiplicationNegPos() {
        App classUnderTest = new App();
        assertEquals(-27, classUnderTest.multiplication(-9, 3));
    }

    @Test public void testAppMultiplicationWithZero() {
        App classUnderTest = new App();
        assertEquals(0, classUnderTest.multiplication(0, 100));
    }

    @Test public void testAppDivisionPosPos() {
        App classUnderTest = new App();
        assertEquals(3, classUnderTest.division(9, 3));
    }

    @Test public void testAppDivisionPosNeg() {
        App classUnderTest = new App();
        assertEquals(-3, classUnderTest.division(9, -3));
    }

    @Test public void testAppDivisionNegPos() {
        App classUnderTest = new App();
        assertEquals(-3, classUnderTest.division(-9, 3));
    }

    @Test public void testAppDivisionNegNeg() {
        App classUnderTest = new App();
        assertEquals(3, classUnderTest.division(-9, -3));
    }

    @Test public void testAppDivisionIfNumeratorIsZero() {
        App classUnderTest = new App();
        assertEquals(0, classUnderTest.division(0, 3));
    }

    @Test public void testAppDivisionIfDenumeratorIsZero() {
        App classUnderTest = new App();
        assertThrows(ArithmeticException.class, classUnderTest.division(3, 0));
    }
}
