/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ristekCalculator;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test public void testAppAdditionPosPos() {
        App classUnderTest = new App();
        assertEquals(15, classUnderTest.addition(8,7));
    }

    @Test public void testAppAdditionPosNeg() {
        App classUnderTest = new App();
        assertEquals(-3, classUnderTest.addition(7,-10));
    }

    @Test public void testAppAdditionNegNeg() {
        App classUnderTest = new App();
        assertEquals(-12, classUnderTest.addition(-9,-3));
    }
}
